# Generated by Django 3.1.6 on 2021-02-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='img_url',
            new_name='image_url',
        ),
    ]
