# Generated by Django 3.1.6 on 2021-02-17 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('reputation_level', models.DecimalField(decimal_places=1, max_digits=2)),
                ('communication_level', models.DecimalField(decimal_places=1, max_digits=2)),
                ('popularity_level', models.DecimalField(decimal_places=1, max_digits=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'makers_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=200)),
                ('event_code', models.CharField(max_length=6)),
                ('maker_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.makerinfo')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
